---
title: "Flights Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggthemes)
library(gghighlight)


df = hflights::hflights
```

# Unique Carrier

Row
--------------------------------------
### Average flights per day

```{r}
avg_flights =round((df %>% tally())/365, 0)
valueBox(avg_flights, icon = "fa-plane", color = "primary")
```

### Number of Origins
```{r}
origins = data.table::uniqueN(df$Origin)
valueBox(origins, icon = "fa-plane-departure", color = "info")
```

### Number of Destinations
```{r}
destinations = data.table::uniqueN(df$Dest)
valueBox(destinations, icon = "fa-plane-arrival", color = "success")
```

Row
-------------------------------------------------
### Late Arrival Flights 

```{r}
  df %>% select(UniqueCarrier, contains("Delay")) %>% 
    group_by(UniqueCarrier) %>%
    filter(ArrDelay > 0) %>% 
    tally() %>%
    ggplot(aes(x = fct_reorder(UniqueCarrier, -n), y = n, 
               fill = factor(ifelse(UniqueCarrier == 'XE', "Highlighted","Normal"))))+
    geom_bar(stat = 'identity') +
    theme_tufte()+
    # gghighlight(max_highlight = 1 )+
    scale_fill_manual(name = "UniqueCarrier", values=c("steelblue","grey"))+
    ggtitle("Flights with Arrival Delay")+
    xlab(" ")+
    ylab(" ")+
    theme(
      plot.title = element_text(color="steel blue", size=14, face="bold"),
      # legend.title = element_blank(),
      legend.position = "none"
      )
```

### Late Departure Flights

```{r}
  df %>% select(UniqueCarrier, contains("Delay")) %>% 
    group_by(UniqueCarrier) %>%
    filter(DepDelay > 0) %>% 
    tally() %>%
    ggplot(aes(x = fct_reorder(UniqueCarrier, -n), y = n, 
               fill = factor(ifelse(UniqueCarrier == 'CO', "Highlighted","Normal"))))+
    geom_bar(stat = 'identity') +
    theme_tufte()+
    gghighlight(max_highlight = 1 )+
    scale_fill_manual(name = "UniqueCarrier", values=c("steelblue","grey"))+
    ggtitle("Flights with Departure Delay")+
    xlab(" ")+
    ylab(" ")+
    theme(
      plot.title = element_text(color="steel blue", size=14, face="bold"),
      # legend.title = element_blank(),
      legend.position = "none"
      )
```

Row
--------------------------------------
### Top 10 Destinations

```{r}
#Top 10 Destinations
df %>% 
  group_by(Dest) %>% tally() %>% 
  arrange(desc(n)) %>% head(10) %>% 
  ggplot(aes(x=fct_reorder(Dest, -n), y=n,
             fill= factor(ifelse(Dest == 'DAL', "Highlighted","Normal"))))+
    geom_bar(stat='identity')+
    scale_fill_manual(values=c("steelblue","grey"))+
  theme_tufte()+
  ggtitle("Top 10 Destinations")+
  xlab(" ")+
  ylab(" ")+
  theme(
    plot.title = element_text(color="steel blue", size=14, face="bold"),
    # legend.title = element_blank(),
    legend.position = "none"
  )
```

### Average Landtime for Each Carrier

```{r}
df %>%
  mutate(land_time=ActualElapsedTime-AirTime) %>%
  group_by(UniqueCarrier) %>%
  summarise(mean_land_time=mean(land_time,na.rm=T)) %>% 
  ggplot(aes(x=fct_reorder(UniqueCarrier, -mean_land_time), y=mean_land_time,
             fill=factor(ifelse(UniqueCarrier == 'YU', "Highlighted", "Normal"))))+
  geom_bar(stat = 'identity')+
  scale_fill_manual(values=c("steelblue","grey"))+
  theme_tufte()+
  ggtitle("Average Landtime for Each Carrier")+
  xlab(" ")+
  ylab(" ")+
  theme(
    plot.title = element_text(color="steel blue", size=14, face="bold"),
    # legend.title = element_blank(),
    legend.position = "none"
  )

```

# Flight Stats

Row
--------------------------------------

### Flights Cancelled
```{r}
rate1 = df %>% 
  select(Cancelled) %>% 
  group_by(Cancelled) %>% 
  summarise(f_count=n()) %>% 
  spread(key = "Cancelled", value = f_count) %>% 
  mutate(per_canceled_origin = (`1`/(`0`+`1`))*100 ) %>% pull() %>% 
  round(2)

 gauge(rate1, min = 0, max = 100, symbol = '%',
       gaugeSectors(
   success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
 ))

```

### Flights Diverted
```{r}
rate2 = df %>% 
  select(Diverted) %>% 
  group_by(Diverted) %>% 
  summarise(f_count=n()) %>% 
  spread(key = "Diverted", value = f_count) %>% 
  mutate(per_canceled_origin = (`1`/(`0`+`1`))*100 ) %>% pull() %>% 
  round(2)

 gauge(rate2, min = 0, max = 100, symbol = '%',
       gaugeSectors(
   success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
 ))

```

### Flights Delayed
```{r}
with_delay = df %>% select(contains("Delay")) %>% 
  filter(ArrDelay > 0| DepDelay > 0) %>% tally() %>% pull 

rate3 = round(with_delay/nrow(df)*100,2)

gauge(rate3, min = 0, max = 100, symbol = '%',
       gaugeSectors(
   success = c(0, 30), warning = c(30, 60), danger = c(60, 100)
 ))

```

Row
--------------------------------------

### Number of flights for Each Destination
```{r}
df2= df %>%   
  group_by(Dest) %>% 
  tally() 

# knitr::kable(df2)

DT::datatable(df2, options = list(
  pageLength = 10
))
```

Row
--------------------------------------

### Number of flights for Each Origin

```{r}
df1= df %>%   
  group_by(Origin) %>% 
  tally() 

knitr::kable(df1)
```

### Average Arrival Delay
```{r}
# For each origin, averge arrival delay
df3 = df %>%
  group_by(Origin) %>% 
  summarise(avg_delay = mean(ArrDelay,na.rm=T))

knitr::kable(df3)
```

